
CREATE TABLE IF NOT EXISTS USUARIO (
	ID INT NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(20) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO1 VARCHAR(50),
	APELLIDO2 VARCHAR(50),
	TELEFONO INT,
	EMAIL VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ROL (
	ID INT NOT NULL AUTO_INCREMENT,
	ROL VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TIPO_VIVIENDA (
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(100) NOT NULL,
	
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS VIVIENDA (
	ID INT NOT NULL AUTO_INCREMENT,
	CALLE VARCHAR(100) NOT NULL,
	NUM INT NOT NULL,
	CODPOSTAL INT NOT NULL,
	POBLACION INT NOT NULL,
	TIPO INT,
	NUMHAB INT,
	PRECIOMES DOUBLE,
	DESCRIPCION VARCHAR(300),
	
	PRIMARY KEY (ID), 
	FOREIGN KEY (TIPO) REFERENCES TIPO_VIVIENDA(ID)
);